/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaAlquiler.java
 *
 * Created on 12-oct-2011, 4:23:13
 */
package treintayplaya;

/**
 *
 * @author sergio
 */
public class AltaAlquiler extends javax.swing.JInternalFrame {

    /** Creates new form AltaAlquiler */
    java.sql.Connection cnx;
    String [] ufID;
    String [] cliID;
    
    public AltaAlquiler() {
        initComponents();
        cnx = Conexion.getInstance().getConnection();
        this.cargaCombos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFecha = new javax.swing.JLabel();
        jlblAlqFecha = new javax.swing.JLabel();
        jlblOperador = new javax.swing.JLabel();
        jlblAlqOperador = new javax.swing.JLabel();
        jlblUF = new javax.swing.JLabel();
        jcbxUF = new javax.swing.JComboBox();
        jlblCliente = new javax.swing.JLabel();
        jcbxCliente = new javax.swing.JComboBox();
        jlblFIN = new javax.swing.JLabel();
        jdcFIN = new com.toedter.calendar.JDateChooser();
        jlblFOUT = new javax.swing.JLabel();
        jdcFOUT = new com.toedter.calendar.JDateChooser();
        jpnlPax = new javax.swing.JPanel();
        jlblCPax = new javax.swing.JLabel();
        jcbxAdultos = new javax.swing.JComboBox();
        jlblAdultos = new javax.swing.JLabel();
        jcbxMenores = new javax.swing.JComboBox();
        jlblMenores = new javax.swing.JLabel();
        jcbxBebes = new javax.swing.JComboBox();
        jlblBebes = new javax.swing.JLabel();
        jcbxDesayunos = new javax.swing.JComboBox();
        jlblDesayunos = new javax.swing.JLabel();
        jlblAlqCPax = new javax.swing.JLabel();
        jlblContrato = new javax.swing.JLabel();
        jcbxContrato = new javax.swing.JComboBox();
        jlblvencimiento = new javax.swing.JLabel();
        jdcVencimiento = new com.toedter.calendar.JDateChooser();
        jlblImporte = new javax.swing.JLabel();
        jftfImporte = new javax.swing.JFormattedTextField();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jpnlDetPagos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jlblCuenta = new javax.swing.JLabel();
        jcbxCuenta = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Alta de Reserva Provisoria");

        jlblFecha.setText("Fecha:");

        jlblAlqFecha.setBackground(new java.awt.Color(255, 255, 255));
        jlblAlqFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblAlqFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlblOperador.setText("Operador:");

        jlblAlqOperador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlblUF.setText("Unidad Funcional:");

        jlblCliente.setText("Inquilino:");

        jcbxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jlblFIN.setText("Fecha IN:");

        jdcFIN.setDateFormatString("dd-MM-yyyy");

        jlblFOUT.setText("Fecha OUT:");

        jdcFOUT.setDateFormatString("dd-MM-yyyy");

        jpnlPax.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblCPax.setText("Ocupantes:");

        jcbxAdultos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jlblAdultos.setText("Adultos");

        jcbxMenores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jlblMenores.setText("Menores");

        jcbxBebes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jlblBebes.setText("Bebes");

        jcbxDesayunos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jlblDesayunos.setText("Desayunos");

        jlblAlqCPax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAlqCPax.setText("0A-0M-0B-0D");
        jlblAlqCPax.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        org.jdesktop.layout.GroupLayout jpnlPaxLayout = new org.jdesktop.layout.GroupLayout(jpnlPax);
        jpnlPax.setLayout(jpnlPaxLayout);
        jpnlPaxLayout.setHorizontalGroup(
            jpnlPaxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlPaxLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlblCPax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jcbxAdultos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlblAdultos)
                .add(18, 18, 18)
                .add(jcbxMenores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlblMenores)
                .add(18, 18, 18)
                .add(jcbxBebes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlblBebes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jcbxDesayunos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlblDesayunos)
                .add(18, 18, 18)
                .add(jlblAlqCPax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlPaxLayout.setVerticalGroup(
            jpnlPaxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnlPaxLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .add(jpnlPaxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblCPax)
                    .add(jcbxAdultos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblAdultos)
                    .add(jcbxMenores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblMenores)
                    .add(jcbxBebes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblBebes)
                    .add(jlblAlqCPax)
                    .add(jcbxDesayunos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblDesayunos))
                .add(7, 7, 7))
        );

        jlblContrato.setText("Contrato:");

        jlblvencimiento.setText("Vencimiento de Reserva:");

        jdcVencimiento.setDateFormatString("dd-MM-yyyy");

        jlblImporte.setText("Importe Total:");

        jftfImporte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jpnlDetPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles de Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setText("Forma de Pago:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Cuenta de Operación:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblCuenta.setText("Cuenta de Imputación:");

        org.jdesktop.layout.GroupLayout jpnlDetPagosLayout = new org.jdesktop.layout.GroupLayout(jpnlDetPagos);
        jpnlDetPagos.setLayout(jpnlDetPagosLayout);
        jpnlDetPagosLayout.setHorizontalGroup(
            jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlDetPagosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45)
                .add(jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .add(jlblCuenta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jcbxCuenta, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jComboBox2, 0, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlDetPagosLayout.setVerticalGroup(
            jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlDetPagosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jpnlDetPagosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblCuenta)
                    .add(jcbxCuenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlDetPagos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jbtnAceptar)
                        .add(18, 18, 18)
                        .add(jbtnCancelar))
                    .add(jpnlPax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jlblFIN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(26, 26, 26)
                                .add(jdcFIN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jlblFecha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jlblUF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(jlblContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jlblAlqFecha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jcbxUF, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jcbxContrato, 0, 263, Short.MAX_VALUE))))
                        .add(44, 44, 44)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jlblImporte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jftfImporte))
                            .add(layout.createSequentialGroup()
                                .add(jlblvencimiento)
                                .add(18, 18, 18)
                                .add(jdcVencimiento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(jlblFOUT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jlblOperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jlblCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jdcFOUT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jlblAlqOperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jcbxCliente, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jlblOperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jlblAlqOperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jlblFecha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jlblAlqFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jcbxUF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jlblUF))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlblCliente)
                        .add(jcbxCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jdcFOUT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jdcFIN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblFIN)
                    .add(jlblFOUT))
                .add(18, 18, 18)
                .add(jpnlPax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlblContrato)
                        .add(jcbxContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jlblvencimiento)
                    .add(jdcVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblImporte)
                    .add(jftfImporte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jpnlDetPagos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnAceptar)
                    .add(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        try {
            java.sql.PreparedStatement pstm = cnx.prepareStatement("insert into Alquileres (alqFecha, alqUF, alqCliente, alqFIN, alqFOUT, alqTotal) values (?, ?, ?, ?, ?, ?)");
            
            pstm.setString(1, jlblFecha.getText());
            pstm.setString(2, jcbxUF.getSelectedItem().toString());
            pstm.setString(3, jcbxCliente.getSelectedItem().toString());
            pstm.setString(4, jdcFIN.getDateFormatString());
            pstm.setString(5, jdcFOUT.getDateFormatString());
            pstm.setString(6, jftfImporte.getText());
            
            int result = pstm.executeUpdate();
            
            if(result == 1) {
                dispose();
            }

        } catch(java.sql.SQLException sqle) {
            
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    public void cargaCombos() {
        try {
            
            jlblAlqFecha.setText(DatosGlobales.getFechaActual());
            
            java.sql.Statement stmUFs       = cnx.createStatement();
            java.sql.Statement stmClientes  = cnx.createStatement();
            
            java.sql.ResultSet rstUFs       = stmUFs.executeQuery("select ufNombre from UnidadesFuncionales order by ufNombre");
            java.sql.ResultSet rstClientes  = stmClientes.executeQuery("select clipApellido from Clientes order by cliApellido");
            
            //ufID = new String[rstUFs.]
            while(rstUFs.next())
                jcbxUF.addItem(rstUFs.getString("ufNombre"));
            
            while(rstClientes.next())
                jcbxCliente.addItem(rstClientes.getString("cliApellido"));
            
            rstUFs.close();
            rstClientes.close();
            
        } catch(java.sql.SQLException sqle) {
            
        }        
    }

//    public static String getFechaActual() {
//        java.util.Date ahora = new java.util.Date();
//        java.text.SimpleDateFormat formateador = new java.text.SimpleDateFormat("dd-MM-yyyy");
//        return formateador.format(ahora);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox jcbxAdultos;
    private javax.swing.JComboBox jcbxBebes;
    private javax.swing.JComboBox jcbxCliente;
    private javax.swing.JComboBox jcbxContrato;
    private javax.swing.JComboBox jcbxCuenta;
    private javax.swing.JComboBox jcbxDesayunos;
    private javax.swing.JComboBox jcbxMenores;
    private javax.swing.JComboBox jcbxUF;
    private com.toedter.calendar.JDateChooser jdcFIN;
    private com.toedter.calendar.JDateChooser jdcFOUT;
    private com.toedter.calendar.JDateChooser jdcVencimiento;
    private javax.swing.JFormattedTextField jftfImporte;
    private javax.swing.JLabel jlblAdultos;
    private javax.swing.JLabel jlblAlqCPax;
    private javax.swing.JLabel jlblAlqFecha;
    private javax.swing.JLabel jlblAlqOperador;
    private javax.swing.JLabel jlblBebes;
    private javax.swing.JLabel jlblCPax;
    private javax.swing.JLabel jlblCliente;
    private javax.swing.JLabel jlblContrato;
    private javax.swing.JLabel jlblCuenta;
    private javax.swing.JLabel jlblDesayunos;
    private javax.swing.JLabel jlblFIN;
    private javax.swing.JLabel jlblFOUT;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblImporte;
    private javax.swing.JLabel jlblMenores;
    private javax.swing.JLabel jlblOperador;
    private javax.swing.JLabel jlblUF;
    private javax.swing.JLabel jlblvencimiento;
    private javax.swing.JPanel jpnlDetPagos;
    private javax.swing.JPanel jpnlPax;
    // End of variables declaration//GEN-END:variables
}
