/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package treintayplaya;

/**
 *
 * @author sergio
 */
public class AltaUF extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaUF
     */
    
    java.sql.Connection cnx;
        
    public AltaUF() {
        initComponents();
        
        try {
            Class.forName("org.gjt.mm.mysql.Driver");

            cnx = java.sql.DriverManager.getConnection("jdbc:mysql://sergioioppolo.com.ar/sdioppolo_typ", "sdioppolo_root", "sdi7346DB");
        } catch(ClassNotFoundException cnfe) {
            
        } catch(java.sql.SQLException sqle) {
            
        }
        
        this.cargaCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jtxfNombre = new javax.swing.JTextField();
        jlblTUF = new javax.swing.JLabel();
        jcbxTUF = new javax.swing.JComboBox();
        jlblPropietario = new javax.swing.JLabel();
        jcbxPropietarios = new javax.swing.JComboBox();
        jlblEquipamiento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxaEquipamiento = new javax.swing.JTextArea();
        jlblTarifa = new javax.swing.JLabel();
        jcbxTarifa = new javax.swing.JComboBox();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jlblComision = new javax.swing.JLabel();
        jftfComision = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Alta de Unidades Funcionales");

        jlblNombre.setText("Nombre:");

        jlblTUF.setText("Tipo de Unidad:");

        jlblPropietario.setText("Propietario:");

        jlblEquipamiento.setText("Equipamiento:");

        jtxaEquipamiento.setColumns(20);
        jtxaEquipamiento.setRows(5);
        jScrollPane2.setViewportView(jtxaEquipamiento);

        jlblTarifa.setText("Tarifa:");

        jcbxTarifa.setEnabled(false);

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jlblComision.setText("Comisión:");

        jftfComision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        jftfComision.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jbtnAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jlblNombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jlblTUF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jlblPropietario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jlblEquipamiento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jlblTarifa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jlblComision))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jtxfNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jcbxTUF, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jcbxPropietarios, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                .add(jcbxTarifa, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jftfComision, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblNombre)
                    .add(jtxfNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblTUF)
                    .add(jcbxTUF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblPropietario)
                    .add(jcbxPropietarios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblEquipamiento)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jcbxTarifa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblTarifa))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblComision)
                    .add(jftfComision, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnAceptar)
                    .add(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        try {
            
            java.sql.Statement stm = cnx.createStatement();
            java.sql.ResultSet rst = stm.executeQuery("select propID from Propietarios where propApellido = '" + jcbxPropietarios.getSelectedItem().toString() + "'");
            
            rst.next();
            String propID = rst.getString(1);
            
            stm.close();
            
            java.sql.PreparedStatement pstm = cnx.prepareStatement("insert into UnidadesFuncionales (ufNombre, ufTipo, ufPropietario, ufDetalles, ufPrecio) values (?, ?, ?, ?, 0)");
            
            pstm.setString(1, jtxfNombre.getText());
            pstm.setString(2, jcbxTUF.getSelectedItem().toString());
            pstm.setString(3, propID);
            pstm.setString(4, jtxaEquipamiento.getText());
            
            int result = pstm.executeUpdate();
            
            if(result == 1) {
                stm = cnx.createStatement();
                rst = stm.executeQuery("select propApellido, propNombre, propTelefono, propCelular, propEmail from Propietarios where propID = '" + propID + "'");

                rst.next();
                String propApe = rst.getString(1);
                String propNom = rst.getString(2);
                String propTel = rst.getString(3);
                String propCel = rst.getString(4);
                String propEma = rst.getString(5);

                stm.close();

                Object [] fila = {jtxfNombre.getText(), jcbxTUF.getSelectedItem().toString(), propApe, propNom, propTel, propCel, propEma};
                ConsultaUF.modelo.addRow(fila);
            }
            
            dispose();
            
        } catch(java.sql.SQLException sqle) {
            sqle.printStackTrace();
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    public void cargaCombos() {
        try {
            
            java.sql.Statement stmPropietarios  = cnx.createStatement();
            java.sql.Statement stmTUF           = cnx.createStatement();
            java.sql.Statement stmTarifas       = cnx.createStatement();
            
            java.sql.ResultSet rstPropietarios  = stmPropietarios.executeQuery("select propApellido from Propietarios order by propUF");
            java.sql.ResultSet rstTUF           = stmTUF.executeQuery("select tufDetalle from TiposUF order by tufDetalle");
            java.sql.ResultSet rstTarifas       = stmTarifas.executeQuery("select tcNombre from TCuentas order by tcNombre");
            
            while(rstPropietarios.next())
                jcbxPropietarios.addItem(rstPropietarios.getString("propApellido"));
            
            while(rstTUF.next())
                jcbxTUF.addItem(rstTUF.getString("tufDetalle"));
            
            rstPropietarios.close();
            rstTUF.close();
            
        } catch(java.sql.SQLException sqle) {
            sqle.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox jcbxPropietarios;
    private javax.swing.JComboBox jcbxTUF;
    private javax.swing.JComboBox jcbxTarifa;
    private javax.swing.JFormattedTextField jftfComision;
    private javax.swing.JLabel jlblComision;
    private javax.swing.JLabel jlblEquipamiento;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblPropietario;
    private javax.swing.JLabel jlblTUF;
    private javax.swing.JLabel jlblTarifa;
    private javax.swing.JTextArea jtxaEquipamiento;
    private javax.swing.JTextField jtxfNombre;
    // End of variables declaration//GEN-END:variables
}
