/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package treintayplaya;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author administrador
 */
public class ConsultaMovimientos extends javax.swing.JInternalFrame {
    private static DefaultTableModel modelo = new DefaultTableModel();
    static java.sql.Connection cnx;
    /**
     * Creates new form ConsultaMovimientos
     */
    public ConsultaMovimientos() {
        cnx = Conexion.getInstance().getConnection();
        initComponents();
        actualizarTabla();
    }
    
    public static void actualizarTabla(){
        try {
            java.sql.Statement stm = cnx.createStatement();
            String query = "SELECT * FROM Movimientos LEFT JOIN UnidadesFuncionales ON movUF = ufID LEFT JOIN TiposPago ON movTipoPago = tpID ORDER BY movFecha DESC";
            java.sql.ResultSet rst = stm.executeQuery(query);
            Vector data = new Vector();
            while(rst.next()){
                Vector row = new Vector();
                row.add(rst.getString("movFecha").substring(0,19));
                row.add(rst.getDouble("movImporte"));
                row.add(rst.getString("tpNombre"));
                row.add(rst.getString("ufNombre"));
                data.add(row);
            }
            Vector headers = new Vector();
            headers.add("Fecha");
            headers.add("Importe");
            headers.add("Tipo de pago");
            headers.add("Unidad Funcional");
            modelo.setDataVector(data, headers);
            rst.close();
            stm.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaMovimientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblMovimientos = new javax.swing.JTable();
        jbtnAgregar = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnCerrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Movimientos");

        jtblMovimientos.setModel(modelo);
        jScrollPane1.setViewportView(jtblMovimientos);

        jbtnAgregar.setMnemonic('A');
        jbtnAgregar.setText("Agregar");

        jbtnBorrar.setMnemonic('B');
        jbtnBorrar.setText("Borrar");

        jbtnActualizar.setMnemonic('t');
        jbtnActualizar.setText("Actualizar");

        jbtnCerrar.setMnemonic('C');
        jbtnCerrar.setText("Cerrar");
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAgregar)
                    .addComponent(jbtnBorrar)
                    .addComponent(jbtnActualizar)
                    .addComponent(jbtnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JTable jtblMovimientos;
    // End of variables declaration//GEN-END:variables
}
