/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package treintayplaya;

import java.sql.SQLException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class ListadoAlquileres extends javax.swing.JInternalFrame {
    final static int DEUDORES=0;
    final static int VENCIMIENTOS=1;
    final static int ENTRANTES=2;
    java.sql.Connection cnx;
    javax.swing.table.DefaultTableModel modelo;
    Integer listado;
    
    /** Creates new form ListadoAlquileres */
    public ListadoAlquileres(Integer listado) {
        cnx = Conexion.getInstance().getConnection();
        modelo = new javax.swing.table.DefaultTableModel();
        this.listado = listado;
        initComponents();
        getRootPane().setDefaultButton(listar);
        listar();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        enviarMail = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable(){     public boolean isCellEditable(int row, int col){         return false;     } };
        jPanel1 = new javax.swing.JPanel();
        fechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        fechaHasta = new com.toedter.calendar.JDateChooser();
        cerrar = new javax.swing.JButton();
        listar = new javax.swing.JButton();

        menu.setComponentPopupMenu(menu);

        enviarMail.setMnemonic('E');
        enviarMail.setText("Enviar e-mail");
        enviarMail.setToolTipText("");
        enviarMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMailActionPerformed(evt);
            }
        });
        menu.add(enviarMail);

        menu.getAccessibleContext().setAccessibleParent(tabla);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(armarTitulo());

        tabla.setModel(modelo);
        tabla.setComponentPopupMenu(menu);
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        fechaDesde.setCalendar(new GregorianCalendar());

        jLabel1.setText("a");

        fechaHasta.setCalendar(FechasFormatter.getMaxToday());

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(fechaDesde, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(fechaHasta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel1)
                    .add(fechaHasta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fechaDesde, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cerrar.setMnemonic('C');
        cerrar.setText("Cerrar");
        cerrar.setToolTipText("");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        listar.setMnemonic('L');
        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(listar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(cerrar))
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(listar)
                    .add(cerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarMailActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
       if(fechaDesde.getCalendar().getTimeInMillis() > fechaHasta.getCalendar().getTimeInMillis()){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha correcta.", "Fecha inválida", JOptionPane.ERROR_MESSAGE);
            fechaHasta.requestFocus();
            tabla.setEnabled(false);
        }else{
            tabla.setEnabled(true);
            listar();
        }
    }//GEN-LAST:event_listarActionPerformed
    
    private void listarDeudores(){
        try {
            String query = "SELECT *, (alqTotal - alqImporteReserva) as Saldo FROM Alquileres, Clientes, UnidadesFuncionales WHERE alqCliente = cliID AND alqUF = ufID AND alqFecha >= ? AND alqFecha <= ? AND (alqTotal - alqImporteReserva) != 0";
            java.sql.PreparedStatement pstm = cnx.prepareStatement(query);
            pstm.setString(1, FechasFormatter.getFechaString(fechaDesde.getCalendar()));
            pstm.setString(2, FechasFormatter.getFechaString(fechaHasta.getCalendar()));
            java.sql.ResultSet rst = pstm.executeQuery();
            
            modelo = new javax.swing.table.DefaultTableModel();
            Object[] headers = {"Apellido", "Nombre", 
                                "Unidad Funcional", "Fecha Reserva", 
                                "Fecha de Ingreso", "Fecha de Egreso", 
                                "Saldo", "E-mail", "Teléfono",
                                "Celular"};
            modelo.setColumnIdentifiers(headers);
            tabla.setModel(modelo);
            while (rst.next()){
                Object[] fila = {rst.getString("cliApellido"),
                                 rst.getString("cliNombre"),
                                 rst.getString("ufNombre"),
                                 FechasFormatter.getFechaSimpleString(rst.getString("alqFecha")),
                                 FechasFormatter.getFechaSimpleString(rst.getString("alqFIN")),
                                 FechasFormatter.getFechaSimpleString(rst.getString("alqFOUT")),
                                 rst.getDouble("Saldo"),
                                 rst.getString("cliEmail"),
                                 rst.getString("cliTelefono"),
                                 rst.getString("cliCelular")};
                modelo.addRow(fila);
            }
            rst.close();
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(ListadoAlquileres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JMenuItem enviarMail;
    private com.toedter.calendar.JDateChooser fechaDesde;
    private com.toedter.calendar.JDateChooser fechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private String armarTitulo() {
        String titulo = "";
        switch(listado){
            case DEUDORES:
                titulo = "Listado de inquilinos deudores";
                break;
            case VENCIMIENTOS:
                titulo = "Listado de reservas vencidas";
                break;
            case ENTRANTES:
                titulo = "Listado de inquilinos entrantes";
                break;
        }
        return titulo;
    }

    private void listar() {
        switch(listado){
            case DEUDORES:
                listarDeudores();
                break;
            case VENCIMIENTOS:
                break;
            case ENTRANTES:
                break;
        }
    }

}
