/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaActividadAdmin.java
 *
 * Created on 11-oct-2011, 11:56:59
 */
package treintayplaya;

/**
 *
 * @author sergio
 */
public class VistaActividadAdmin extends javax.swing.JInternalFrame {

    /** Creates new form VistaActividadAdmin */
    public VistaActividadAdmin() {
        initComponents();
        jtblVistaMensual.setDefaultRenderer(Object.class, new MiRender());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmEstado = new javax.swing.JPopupMenu();
        reservarMenuItem = new javax.swing.JMenuItem();
        confirmarMenuItem = new javax.swing.JMenuItem();
        cerrarMenuItem = new javax.swing.JMenuItem();
        anularMenuItem = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnAnterior = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jlblMes = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jbtnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVistaMensual = new javax.swing.JTable();

        jpmEstado.setComponentPopupMenu(jpmEstado);

        reservarMenuItem.setText("Reservar");
        reservarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarMenuItemActionPerformed(evt);
            }
        });
        jpmEstado.add(reservarMenuItem);

        confirmarMenuItem.setText("Confirmar Reserva");
        confirmarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarMenuItemActionPerformed(evt);
            }
        });
        jpmEstado.add(confirmarMenuItem);

        cerrarMenuItem.setText("Cerrar Contrato");
        cerrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMenuItemActionPerformed(evt);
            }
        });
        jpmEstado.add(cerrarMenuItem);

        anularMenuItem.setText("Anular");
        anularMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularMenuItemActionPerformed(evt);
            }
        });
        jpmEstado.add(anularMenuItem);

        jpmEstado.getAccessibleContext().setAccessibleParent(jtblVistaMensual);

        setClosable(true);
        setResizable(true);
        setTitle("Vista de Actividad Mensual");
        setMinimumSize(new java.awt.Dimension(1020, 640));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jbtnAnterior.setText("Anterior");
        jbtnAnterior.setFocusable(false);
        jbtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbtnAnterior);
        jToolBar1.add(filler1);

        jlblMes.setText("Mes Actual");
        jToolBar1.add(jlblMes);
        jToolBar1.add(filler2);

        jbtnSiguiente.setText("Siguiente");
        jbtnSiguiente.setFocusable(false);
        jbtnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbtnSiguiente);

        jScrollPane1.setRowHeaderView(null);

        jtblVistaMensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UF", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
            }
        ));
        jtblVistaMensual.setCellSelectionEnabled(true);
        jtblVistaMensual.setComponentPopupMenu(jpmEstado);
        jtblVistaMensual.setGridColor(new java.awt.Color(204, 204, 204));
        jtblVistaMensual.setShowGrid(true);
        jtblVistaMensual.getTableHeader().setResizingAllowed(false);
        jtblVistaMensual.getTableHeader().setReorderingAllowed(false);
        jtblVistaMensual.setValueAt("2 AMB al Frente", 0, 0);
        jtblVistaMensual.setValueAt("UF 1", 1, 0);
        jtblVistaMensual.setValueAt("UF 2", 2, 0);
        jtblVistaMensual.setValueAt("UF 4", 3, 0);
        jtblVistaMensual.setValueAt("UF 6", 4, 0);
        jtblVistaMensual.setValueAt("UF 12", 5, 0);
        jtblVistaMensual.setValueAt("UF 13", 6, 0);
        jtblVistaMensual.setValueAt("UF 17", 7, 0);
        jtblVistaMensual.setValueAt("UF 22 A", 8, 0);
        jtblVistaMensual.setValueAt("UF 24", 9, 0);
        jtblVistaMensual.setValueAt("UF 28", 10, 0);

        jtblVistaMensual.setValueAt("3 AMB 1 BÑ al Frente", 11, 0);
        jtblVistaMensual.setValueAt("UF 23", 12, 0);

        jtblVistaMensual.setValueAt("3 AMB 1 BÑ Lateral", 13, 0);
        jtblVistaMensual.setValueAt("UF 7", 14, 0);
        jtblVistaMensual.setValueAt("UF 9", 15, 0);
        jtblVistaMensual.setValueAt("UF 11", 16, 0);
        jtblVistaMensual.setValueAt("UF 18", 17, 0);
        jtblVistaMensual.setValueAt("UF 20", 18, 0);

        jtblVistaMensual.setValueAt("3 AMB 2 BÑ al Frente", 19, 0);
        jtblVistaMensual.setValueAt("UF 3", 20, 0);
        jtblVistaMensual.setValueAt("UF 5", 21, 0);
        jtblVistaMensual.setValueAt("UF 14", 22, 0);
        jtblVistaMensual.setValueAt("UF 16", 23, 0);
        jtblVistaMensual.setValueAt("UF 15", 24, 0);
        jtblVistaMensual.setValueAt("UF 26", 25, 0);
        jtblVistaMensual.setValueAt("UF 25", 26, 0);
        jtblVistaMensual.setValueAt("UF 27", 27, 0);
        jtblVistaMensual.setValueAt("4 AMB 2 BÑ Lateral", 28, 0);
        jScrollPane1.setViewportView(jtblVistaMensual);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarMenuItemActionPerformed
        for(int celda = 0; celda < jtblVistaMensual.getColumnCount(); celda++) {
            if (jtblVistaMensual.isCellSelected(jtblVistaMensual.getSelectedRow(), celda)) {
                jtblVistaMensual.setValueAt(">>", jtblVistaMensual.getSelectedRow(), celda);
            }
        }
        jtblVistaMensual.setDefaultRenderer(Object.class, new MiRender());
        if(DatosGlobales.usrNivel == 1 && DatosGlobales.usrEstado == 1 && DatosGlobales.appSesion) {
            AltaAlquiler aAlquiler = new AltaAlquiler();
            AppPrincipal.desktopPane.add(aAlquiler);
            aAlquiler.show();
            aAlquiler.toFront();
        }
    }//GEN-LAST:event_reservarMenuItemActionPerformed

    private void confirmarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarMenuItemActionPerformed
        for(int celda = 0; celda < jtblVistaMensual.getColumnCount(); celda++) {
            if (jtblVistaMensual.isCellSelected(jtblVistaMensual.getSelectedRow(), celda)) {
                jtblVistaMensual.setValueAt("^^", jtblVistaMensual.getSelectedRow(), celda);
            }
        }
        jtblVistaMensual.setDefaultRenderer(Object.class, new MiRender());

//        if(DatosGlobales.usrNivel == 1 && DatosGlobales.usrEstado == 1 && DatosGlobales.appSesion) {
//            AltaAlquiler aAlquiler = new AltaAlquiler();
//            AppPrincipal.desktopPane.add(aAlquiler);
//            aAlquiler.show();
//        }
    }//GEN-LAST:event_confirmarMenuItemActionPerformed

    private void cerrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMenuItemActionPerformed
        for(int celda = 0; celda < jtblVistaMensual.getColumnCount(); celda++) {
            if (jtblVistaMensual.isCellSelected(jtblVistaMensual.getSelectedRow(), celda)) {
                jtblVistaMensual.setValueAt("00", jtblVistaMensual.getSelectedRow(), celda);
            }
        }
        jtblVistaMensual.setDefaultRenderer(Object.class, new MiRender());
    }//GEN-LAST:event_cerrarMenuItemActionPerformed

    private void anularMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularMenuItemActionPerformed
        for(int celda = 0; celda < jtblVistaMensual.getColumnCount(); celda++) {
            if (jtblVistaMensual.isCellSelected(jtblVistaMensual.getSelectedRow(), celda)) {
                jtblVistaMensual.setValueAt("", jtblVistaMensual.getSelectedRow(), celda);
            }
        }
        jtblVistaMensual.setDefaultRenderer(Object.class, new MiRender());
    }//GEN-LAST:event_anularMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anularMenuItem;
    private javax.swing.JMenuItem cerrarMenuItem;
    private javax.swing.JMenuItem confirmarMenuItem;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAnterior;
    private javax.swing.JButton jbtnSiguiente;
    private javax.swing.JLabel jlblMes;
    private javax.swing.JPopupMenu jpmEstado;
    private javax.swing.JTable jtblVistaMensual;
    private javax.swing.JMenuItem reservarMenuItem;
    // End of variables declaration//GEN-END:variables
}
