/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistroUsuarios.java
 *
 * Created on 02-oct-2011, 17:51:07
 */
package treintayplaya;

/**
 *
 * @author sergio
 */
public class RegistroUsuarios extends javax.swing.JFrame {

    /** Creates new form RegistroUsuarios */
    public RegistroUsuarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jlblUsuario = new javax.swing.JLabel();
        jtxfUsuario = new javax.swing.JTextField();
        jlblPass = new javax.swing.JLabel();
        jpfPass = new javax.swing.JPasswordField();
        jlblValidaPass = new javax.swing.JLabel();
        jpfPassVal = new javax.swing.JPasswordField();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registración de Usuarios Web");
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLayeredPane2.setBackground(new java.awt.Color(176, 209, 214));

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jbtnAceptar.setBounds(190, 150, 92, 29);
        jLayeredPane2.add(jbtnAceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jbtnCancelar.setBounds(290, 150, 98, 29);
        jLayeredPane2.add(jbtnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlblUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlblUsuario.setText("Usuario:");
        jlblUsuario.setToolTipText("Dirección de Correo Electrónico.");
        jlblUsuario.setBounds(10, 10, 80, 16);
        jLayeredPane2.add(jlblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jtxfUsuario.setToolTipText("Dirección de Correo Electrónico.");
        jtxfUsuario.setBounds(170, 0, 220, 28);
        jLayeredPane2.add(jtxfUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlblPass.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlblPass.setForeground(new java.awt.Color(255, 255, 255));
        jlblPass.setText("Contraseña:");
        jlblPass.setBounds(10, 50, 90, 16);
        jLayeredPane2.add(jlblPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpfPass.setBounds(170, 40, 140, 28);
        jLayeredPane2.add(jpfPass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlblValidaPass.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlblValidaPass.setForeground(new java.awt.Color(255, 255, 255));
        jlblValidaPass.setText("Validar Contraseña:");
        jlblValidaPass.setBounds(10, 90, 140, 16);
        jLayeredPane2.add(jlblValidaPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpfPassVal.setBounds(170, 80, 140, 28);
        jLayeredPane2.add(jpfPassVal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(10, 100, 410, 180);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/treintayplaya/imagenes/02.jpg"))); // NOI18N
        jlblFondo.setBounds(10, 0, 644, 290);
        jLayeredPane1.add(jlblFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_jbtnCancelarActionPerformed

private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
// TODO add your handling code here:
    
    boolean valEmail, valPass;
    
    valEmail = valPass = false;
    
    // Valida Dirección de E-Mail

    if(!validaEmail(jtxfUsuario.getText())) {
        javax.swing.JOptionPane.showMessageDialog(this,
                                                  "Ingresó una Dirección de Correo Electrónico NO Válido.",
                                                  "Error",
                                                  javax.swing.JOptionPane.ERROR_MESSAGE);
        
        jtxfUsuario.setText("");
        jtxfUsuario.requestFocus();
    } else {
        valEmail = true;
    }
    
    
    // Valida Pass
        
    if(!validaPass(new String(jpfPass.getPassword()), new String(jpfPassVal.getPassword()))) {
        javax.swing.JOptionPane.showMessageDialog(this,
                                                  "Las Contraseñas NO Coinciden.",
                                                  "Error",
                                                  javax.swing.JOptionPane.ERROR_MESSAGE);
        jpfPass.setText("");
        jpfPassVal.setText("");
        jpfPass.requestFocus();
    } else {
        valPass = true;
    }
    
    // Agregar el Usuario a la Base
    if(valEmail && valPass) {
        try {

            Class.forName("org.gjt.mm.mysql.Driver");
            java.sql.Connection cnx = java.sql.DriverManager.getConnection("jdbc:mysql://sergioioppolo.com.ar:3306/sdioppolo_typ", "sdioppolo_root", "sdi7346DB");

            java.sql.PreparedStatement pstm = cnx.prepareStatement("insert into UsuariosWeb (usrEmail, usrPass, usrNivel, usrActivo) values (?,AES_ENCRYPT(?,'typ2012'),?,?)") ;

            pstm.setString(1, jtxfUsuario.getText());
            pstm.setString(2, String.valueOf(jpfPass.getPassword())/*toString()*/);
            pstm.setInt(3, 1);
            pstm.setInt(4, 1);

            int resultado = pstm.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "El Usuario Se Registró Correctamente.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            cnx.close();
            
        } catch (ClassNotFoundException cnfe) {
            javax.swing.JOptionPane.showMessageDialog(this, cnfe.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        } catch (java.sql.SQLException sqle) {
            javax.swing.JOptionPane.showMessageDialog(this, sqle.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        dispose();
    }
}//GEN-LAST:event_jbtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new RegistroUsuarios().setVisible(true);
            }
        });
    }
    
    private boolean validaEmail(String email) {
        boolean resultado = false;
        int contAT = 0;
        int posAT = 0;
        int contPunto = 0;
        
        for(int i = 0; i < email.length(); i++)
            if(email.charAt(i) == '@') {
                contAT++;
                posAT = i;
            }
        
        for(int i = posAT; i < email.length(); i++)    
            if(email.charAt(i) == '.')
                contPunto++;
        
        
        if(contAT == 1 && contPunto >= 1)
            resultado = true;
        
        return resultado;
    }
    
    private boolean validaPass(String pass, String passVal) {
        boolean resultado = false;
        
        if(pass.equals(passVal))
            resultado = true;
        
        return resultado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JLabel jlblValidaPass;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JPasswordField jpfPassVal;
    private javax.swing.JTextField jtxfUsuario;
    // End of variables declaration//GEN-END:variables
}
